#if ATARASY_UI_TEST_FIXTURES
import Foundation
import SwiftUI
import AtarasyCore

// Recorded synthetic service responses. No network, provider, or real authenticator is used here.
private enum DigitalFixtureData {
    static let bytes = Data(base64Encoded: "ewogICJzZXJ2aWNlQmFzZSI6ICIyNWQ4Y2E3IiwKICAic2NvcGUiOiAiU3ludGhldGljIFBvc3RncmVTUUwgSFRUUCBwcmVwYXJlIGFuZCBkZWNpc2lvbiByZXN1bHQ7IG5vIHByb3ZpZGVyIG9yIG5hdGl2ZSBhdXRoZW50aWNhdG9yLiIsCiAgImVudmlyb25tZW50IjogewogICAgIm5hbWUiOiAidGVzdCIsCiAgICAib3JpZ2luIjogImh0dHBzOi8vdW5pdC5leGFtcGxlIgogIH0sCiAgInNlc3Npb24iOiB7CiAgICAiaWQiOiAiNDRhZDVjMTctZDdiMy00OGNmLWJiMzYtMjhlOTk3ZDJmNDIwIiwKICAgICJob3VzZWhvbGQiOiAia2V5OnlscjZNTWNESXdWZmI1M20xWUlKa2x0VWJ0VnhyNkkzOFVHZC04ZjF3QWciLAogICAgInByZXNlbnRlcnMiOiBbCiAgICAgICJtZXJjaGFudC0xIgogICAgXSwKICAgICJleHBpcmVzQXQiOiAxODAwMDAwMDkwMDAxCiAgfSwKICAiZGV0YWlsIjogewogICAgImlkIjogIjlmOThlZmE3LWI0MTQtNDMwZS1hZTU1LWY1MWJkZDZlYzJlNyIsCiAgICAiYmluZGluZyI6ICJkaWdpdGFsIiwKICAgICJob3VzZWhvbGQiOiAia2V5OnlscjZNTWNESXdWZmI1M20xWUlKa2x0VWJ0VnhyNkkzOFVHZC04ZjF3QWciLAogICAgInByZXNlbnRlciI6ICJtZXJjaGFudC0xIiwKICAgICJwcmVzZW50ZXJfYXR0ZXN0ZWQiOiBmYWxzZSwKICAgICJwdXJwb3NlIjogInJlcGxlbmlzaCIsCiAgICAicHJpY2VfYmFuZCI6IG51bGwsCiAgICAiZ2l2ZXIiOiBudWxsLAogICAgImNvbmZpZ192ZXJzaW9uIjogImRpZ2l0YWwtY2ZnIiwKICAgICJwcmVzZW50ZWRfYXQiOiAxODAwMDAwMDAwMDAxLAogICAgImV4cGlyZXNfYXQiOiAxODAwMDAzNjAwMDAwLAogICAgInN0YXRlIjogInByZXNlbnRlZCIsCiAgICAiZGVjaWRlZF9hdCI6IG51bGwsCiAgICAiZXhwbG9yYXRpb25fZmxvb3JfbWV0IjogdHJ1ZSwKICAgICJtYW5kYXRlIjogImtleTp5bHI2TU1jREl3VmZiNTNtMVlJSmtsdFVidFZ4cjZJMzhVR2QtOGYxd0FnLjEiLAogICAgImNhbmRpZGF0ZXMiOiBbCiAgICAgIHsKICAgICAgICAiaWQiOiAiNjZmMGY3YjgtNDg2YS00N2M5LTliOGUtZDZjNGM1YzRmZmE5IiwKICAgICAgICAicHJvZHVjdCI6ICJkaWdpdGFsLXRlYSIsCiAgICAgICAgInF1YW50aXR5IjogMSwKICAgICAgICAidW5pdF9wcmljZSI6IDEyMDAsCiAgICAgICAgIm1lcmNoYW50IjogIm1ha2VyLWEiLAogICAgICAgICJtYWtlciI6ICJtYWRlLWJ5LXRlYSIsCiAgICAgICAgInNoaXBzIjogImNhcnJpZXItYSIsCiAgICAgICAgImNhdGVnb3J5IjogbnVsbCwKICAgICAgICAicHJlZGljdGVkX2NvbnZlcnNpb24iOiBudWxsLAogICAgICAgICJpc19leHBsb3JhdGlvbiI6IHRydWUsCiAgICAgICAgImdpdmVuX2J5IjogbnVsbCwKICAgICAgICAidmFsZW5jZSI6ICJvZmZlcmVkIiwKICAgICAgICAiZGVjaWRlZF9hdCI6IG51bGwsCiAgICAgICAgImtlcHRfYXMiOiBudWxsLAogICAgICAgICJsaW5lYWdlIjogbnVsbCwKICAgICAgICAiY29sbGVjdGVkX2FzIjogbnVsbAogICAgICB9CiAgICBdLAogICAgImRpc2Nsb3N1cmVzIjogWwogICAgICB7CiAgICAgICAgIm1lcmNoYW50IjogIm1ha2VyLWEiLAogICAgICAgICJwcm9kdWN0IjogbnVsbCwKICAgICAgICAidmVyc2lvbiI6ICJkLTEiLAogICAgICAgICJpdGVtcyI6IFsKICAgICAgICAgIHsKICAgICAgICAgICAgImxhYmVsIjogInBheW1lbnQiLAogICAgICAgICAgICAidmFsdWUiOiAiY2hhcmdlZCB3aGVuIHRoZSBob3VzZWhvbGQgY29uZmlybXMiCiAgICAgICAgICB9LAogICAgICAgICAgewogICAgICAgICAgICAibGFiZWwiOiAiZGVsaXZlcnkiLAogICAgICAgICAgICAidmFsdWUiOiAiYWxyZWFkeSBwbGFjZWQiCiAgICAgICAgICB9LAogICAgICAgICAgewogICAgICAgICAgICAibGFiZWwiOiAicmV0dXJucyIsCiAgICAgICAgICAgICJ2YWx1ZSI6ICJhcyB0aGUgbWVyY2hhbnQgcHVibGlzaGVkIgogICAgICAgICAgfQogICAgICAgIF0sCiAgICAgICAgInNpZ25hdHVyZSI6ICI1MlBJbWl2U013RjVvWnVOVjkwNmsyR1gzQXRqaVRDZjRlNE5CNjFIeDB3RW5QeFZhbkZub1I5YmgrYVNvcUxNSDN2bUtmbjN1ejluaUlSbG1nMmpBUT09IgogICAgICB9CiAgICBdCiAgfSwKICAicHJlcGFyZWQiOiB7CiAgICAicHJvZmlsZSI6ICJhdGFyYXN5Lm1lbWJlci1kZWNpc2lvbi1hdXRob3Jpc2F0aW9uLjEiLAogICAgIm9wZXJhdGlvbklEIjogIjEyN2I1OTFjLTEyYWYtNDM2NS04NjJiLTJjMzA5OGRjMmZkMiIsCiAgICAicmVxdWVzdERpZ2VzdCI6ICJjMDYzOTkyYWUwNDUxZjY4MmY0ZDU5ZDNiN2RhYTRiNzcyMTQ4MmZjM2UyYWY1YTMzMzUyNzY2NzViN2RlYjQwIiwKICAgICJyZXZpZXdlZFJldmlzaW9uIjogIjZkYjk3YzcxMDM5ZTMzNGQ4ZjRjMGZkMjRmMzU1N2VlMTI3YTU5MTFmMGQ0NzU3NWIzNDYzZGNmMDc3YTdmMjEiLAogICAgImV4cGlyZXNBdCI6IDE4MDAwMDAwNjAwMDEsCiAgICAiY2Fub25pY2FsIjogIjlmOThlZmE3LWI0MTQtNDMwZS1hZTU1LWY1MWJkZDZlYzJlN1xuNjZmMGY3YjgtNDg2YS00N2M5LTliOGUtZDZjNGM1YzRmZmE5OmtlcHQ6c2VsZjoiLAogICAgInJldmlldyI6IHsKICAgICAgImFwcHJvdmFsIjogewogICAgICAgICJvZmZlciI6ICI5Zjk4ZWZhNy1iNDE0LTQzMGUtYWU1NS1mNTFiZGQ2ZWMyZTciLAogICAgICAgICJwcmVzZW50ZXIiOiAibWVyY2hhbnQtMSIsCiAgICAgICAgImV4cGlyZXNfYXQiOiAxODAwMDAzNjAwMDAwLAogICAgICAgICJjYXJyaWFnZSI6IDU1MCwKICAgICAgICAicmVtaW5kZWQiOiBmYWxzZSwKICAgICAgICAibWFuZGF0ZSI6IHsKICAgICAgICAgICJraW5kIjogInN0YW5kaW5nIiwKICAgICAgICAgICJzY29wZSI6ICJUZXN0IHN1cHBsaWVzIiwKICAgICAgICAgICJsYXBzZXNfYXQiOiAxODAwMDEwMDAwMDAwCiAgICAgICAgfSwKICAgICAgICAicHJpY2VfYmFuZCI6IG51bGwsCiAgICAgICAgImRpc2Nsb3N1cmVzIjogWwogICAgICAgICAgewogICAgICAgICAgICAibWVyY2hhbnQiOiAibWFrZXItYSIsCiAgICAgICAgICAgICJwcm9kdWN0IjogbnVsbCwKICAgICAgICAgICAgInZlcnNpb24iOiAiZC0xIiwKICAgICAgICAgICAgIml0ZW1zIjogWwogICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICJsYWJlbCI6ICJwYXltZW50IiwKICAgICAgICAgICAgICAgICJ2YWx1ZSI6ICJjaGFyZ2VkIHdoZW4gdGhlIGhvdXNlaG9sZCBjb25maXJtcyIKICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICJsYWJlbCI6ICJkZWxpdmVyeSIsCiAgICAgICAgICAgICAgICAidmFsdWUiOiAiYWxyZWFkeSBwbGFjZWQiCiAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAibGFiZWwiOiAicmV0dXJucyIsCiAgICAgICAgICAgICAgICAidmFsdWUiOiAiYXMgdGhlIG1lcmNoYW50IHB1Ymxpc2hlZCIKICAgICAgICAgICAgICB9CiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJzaWduYXR1cmUiOiAiNTJQSW1pdlNNd0Y1b1p1TlY5MDZrMkdYM0F0amlUQ2Y0ZTROQjYxSHgwd0VuUHhWYW5Gbm9SOWJoK2FTb3FMTUgzdm1LZm4zdXo5bmlJUmxtZzJqQVE9PSIKICAgICAgICAgIH0KICAgICAgICBdLAogICAgICAgICJjYW5kaWRhdGVzIjogWwogICAgICAgICAgewogICAgICAgICAgICAiaWQiOiAiNjZmMGY3YjgtNDg2YS00N2M5LTliOGUtZDZjNGM1YzRmZmE5IiwKICAgICAgICAgICAgInByb2R1Y3QiOiAiZGlnaXRhbC10ZWEiLAogICAgICAgICAgICAicXVhbnRpdHkiOiAxLAogICAgICAgICAgICAidW5pdF9wcmljZSI6IDEyMDAsCiAgICAgICAgICAgICJtZXJjaGFudCI6ICJtYWtlci1hIiwKICAgICAgICAgICAgIm1ha2VyIjogIm1hZGUtYnktdGVhIiwKICAgICAgICAgICAgImdpdmVuX2J5IjogbnVsbCwKICAgICAgICAgICAgInNoaXBzIjogImNhcnJpZXItYSIsCiAgICAgICAgICAgICJpc19leHBsb3JhdGlvbiI6IHRydWUsCiAgICAgICAgICAgICJ2YWxlbmNlIjogIm9mZmVyZWQiLAogICAgICAgICAgICAiY29sbGVjdGVkX2FzIjogbnVsbCwKICAgICAgICAgICAgImFsdGVybmF0aXZlcyI6IFsKICAgICAgICAgICAgICAiVXNlIGV4aXN0aW5nIHN1cHBsaWVzIgogICAgICAgICAgICBdLAogICAgICAgICAgICAiYXJndW1lbnRfYWdhaW5zdCI6ICJZb3UgbWF5IGFscmVhZHkgaGF2ZSBlbm91Z2guIiwKICAgICAgICAgICAgImRpc2Nsb3N1cmUiOiB7CiAgICAgICAgICAgICAgIm1lcmNoYW50IjogIm1ha2VyLWEiLAogICAgICAgICAgICAgICJwcm9kdWN0IjogbnVsbAogICAgICAgICAgICB9CiAgICAgICAgICB9CiAgICAgICAgXSwKICAgICAgICAiZXhjbHVkZWQiOiBbXQogICAgICB9LAogICAgICAibWFuZGF0ZSI6IHsKICAgICAgICAiY2VpbGluZ19vdXRfb2ZfbmV0d29yayI6IDEwMDAwLAogICAgICAgICJjZWlsaW5nX2RhaWx5IjogbnVsbCwKICAgICAgICAiY29vbGluZ19zZWNvbmRzIjogbnVsbCwKICAgICAgICAiY29fc2lnbmVycyI6IFtdLAogICAgICAgICJsYXBzZXNfYXQiOiAxODAwMDEwMDAwMDAwLAogICAgICAgICJ2ZXJzaW9uIjogMSwKICAgICAgICAiaWQiOiAia2V5OnlscjZNTWNESXdWZmI1M20xWUlKa2x0VWJ0VnhyNkkzOFVHZC04ZjF3QWcuMSIsCiAgICAgICAgImhvdXNlaG9sZCI6ICJrZXk6eWxyNk1NY0RJd1ZmYjUzbTFZSUprbHRVYnRWeHI2STM4VUdkLThmMXdBZyIKICAgICAgfSwKICAgICAgImRlY2lzaW9ucyI6IFsKICAgICAgICB7CiAgICAgICAgICAiY2FuZGlkYXRlIjogIjY2ZjBmN2I4LTQ4NmEtNDdjOS05YjhlLWQ2YzRjNWM0ZmZhOSIsCiAgICAgICAgICAidmFsZW5jZSI6ICJrZXB0IiwKICAgICAgICAgICJrZXB0X2FzIjogInNlbGYiCiAgICAgICAgfQogICAgICBdLAogICAgICAiZ29vZHMiOiAxMjAwLAogICAgICAiY2FycmlhZ2UiOiA1NTAsCiAgICAgICJ0b3RhbCI6IDE3NTAKICAgIH0sCiAgICAib3BlcmF0aW9uU3RhdGUiOiAicHJlcGFyZWQiLAogICAgInB1YmxpY0tleSI6IHsKICAgICAgImNoYWxsZW5nZSI6ICJ3UkIwaTc4ZHJDNWFXRFdzem1iTE4tdDN4QWZjWHFLWXhJRDRLZlZVa2dZIiwKICAgICAgInJwSWQiOiAidW5pdC5leGFtcGxlIiwKICAgICAgInVzZXJWZXJpZmljYXRpb24iOiAicmVxdWlyZWQiLAogICAgICAiYWxsb3dDcmVkZW50aWFscyI6IFsKICAgICAgICB7CiAgICAgICAgICAidHlwZSI6ICJwdWJsaWMta2V5IiwKICAgICAgICAgICJpZCI6ICJabXlvb084ZUgtRmFMU3hBc0IwTVlKSGNGTFFONkNnUDdtYTJtVVVyWVAwIgogICAgICAgIH0KICAgICAgXQogICAgfQogIH0sCiAgImNvbW1pdHRlZCI6IHsKICAgICJvcGVyYXRpb25JRCI6ICIxMjdiNTkxYy0xMmFmLTQzNjUtODYyYi0yYzMwOThkYzJmZDIiLAogICAgIm9wZXJhdGlvblN0YXRlIjogImNvbW1pdHRlZCIsCiAgICAiZGVjaXNpb24iOiB7CiAgICAgICJpZCI6ICI5Zjk4ZWZhNy1iNDE0LTQzMGUtYWU1NS1mNTFiZGQ2ZWMyZTciLAogICAgICAiYmluZGluZyI6ICJkaWdpdGFsIiwKICAgICAgImhvdXNlaG9sZCI6ICJrZXk6eWxyNk1NY0RJd1ZmYjUzbTFZSUprbHRVYnRWeHI2STM4VUdkLThmMXdBZyIsCiAgICAgICJwcmVzZW50ZXIiOiAibWVyY2hhbnQtMSIsCiAgICAgICJwdXJwb3NlIjogInJlcGxlbmlzaCIsCiAgICAgICJwcmVzZW50ZXJfYXR0ZXN0ZWQiOiBmYWxzZSwKICAgICAgInByaWNlX2JhbmQiOiBudWxsLAogICAgICAiZ2l2ZXIiOiBudWxsLAogICAgICAiY29uZmlnX3ZlcnNpb24iOiAiZGlnaXRhbC1jZmciLAogICAgICAicHJlc2VudGVkX2F0IjogMTgwMDAwMDAwMDAwMSwKICAgICAgImV4cGlyZXNfYXQiOiAxODAwMDAzNjAwMDAwLAogICAgICAic3RhdGUiOiAiZGVjaWRlZCIsCiAgICAgICJleHBsb3JhdGlvbl9mbG9vcl9tZXQiOiB0cnVlLAogICAgICAibWFuZGF0ZSI6ICJrZXk6eWxyNk1NY0RJd1ZmYjUzbTFZSUprbHRVYnRWeHI2STM4VUdkLThmMXdBZy4xIiwKICAgICAgImNhbmRpZGF0ZXMiOiBbCiAgICAgICAgewogICAgICAgICAgImlkIjogIjY2ZjBmN2I4LTQ4NmEtNDdjOS05YjhlLWQ2YzRjNWM0ZmZhOSIsCiAgICAgICAgICAicHJvZHVjdCI6ICJkaWdpdGFsLXRlYSIsCiAgICAgICAgICAicXVhbnRpdHkiOiAxLAogICAgICAgICAgInVuaXRfcHJpY2UiOiAxMjAwLAogICAgICAgICAgIm1lcmNoYW50IjogIm1ha2VyLWEiLAogICAgICAgICAgIm1ha2VyIjogIm1hZGUtYnktdGVhIiwKICAgICAgICAgICJzaGlwcyI6ICJjYXJyaWVyLWEiLAogICAgICAgICAgImNhdGVnb3J5IjogbnVsbCwKICAgICAgICAgICJwcmVkaWN0ZWRfY29udmVyc2lvbiI6IG51bGwsCiAgICAgICAgICAiaXNfZXhwbG9yYXRpb24iOiB0cnVlLAogICAgICAgICAgImdpdmVuX2J5IjogbnVsbCwKICAgICAgICAgICJ2YWxlbmNlIjogImtlcHQiLAogICAgICAgICAgImRlY2lkZWRfYXQiOiAxODAwMDAwMDAwMDAxLAogICAgICAgICAgImtlcHRfYXMiOiAic2VsZiIsCiAgICAgICAgICAibGluZWFnZSI6IG51bGwKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJkaXNjbG9zdXJlcyI6IFsKICAgICAgICB7CiAgICAgICAgICAibWVyY2hhbnQiOiAibWFrZXItYSIsCiAgICAgICAgICAicHJvZHVjdCI6IG51bGwsCiAgICAgICAgICAidmVyc2lvbiI6ICJkLTEiLAogICAgICAgICAgIml0ZW1zIjogWwogICAgICAgICAgICB7CiAgICAgICAgICAgICAgImxhYmVsIjogInBheW1lbnQiLAogICAgICAgICAgICAgICJ2YWx1ZSI6ICJjaGFyZ2VkIHdoZW4gdGhlIGhvdXNlaG9sZCBjb25maXJtcyIKICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICJsYWJlbCI6ICJkZWxpdmVyeSIsCiAgICAgICAgICAgICAgInZhbHVlIjogImFscmVhZHkgcGxhY2VkIgogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgImxhYmVsIjogInJldHVybnMiLAogICAgICAgICAgICAgICJ2YWx1ZSI6ICJhcyB0aGUgbWVyY2hhbnQgcHVibGlzaGVkIgogICAgICAgICAgICB9CiAgICAgICAgICBdLAogICAgICAgICAgInNpZ25hdHVyZSI6ICI1MlBJbWl2U013RjVvWnVOVjkwNmsyR1gzQXRqaVRDZjRlNE5CNjFIeDB3RW5QeFZhbkZub1I5YmgrYVNvcUxNSDN2bUtmbjN1ejluaUlSbG1nMmpBUT09IgogICAgICAgIH0KICAgICAgXSwKICAgICAgInJlbWluZGVyc19zZW50IjogMCwKICAgICAgImRlY2lkZWRfYXQiOiAxODAwMDAwMDAwMDAxCiAgICB9CiAgfQp9Cg==")!
    static var value: [String: Any] { try! JSONSerialization.jsonObject(with: bytes) as! [String: Any] }
    static func data(_ key: String) -> Data { try! JSONSerialization.data(withJSONObject: value[key]!) }
}
private struct DigitalFixtureVault: MemberSessionVault {
    let info: MemberSessionInfo
    func load(environment: MemberEnvironment, household: String) throws -> StoredMemberSession? {
        let object: [String: Any] = ["token": "amr1_" + String(repeating: "A", count: 43), "info": try JSONSerialization.jsonObject(with: JSONEncoder().encode(info))]
        return try JSONDecoder().decode(StoredMemberSession.self, from: JSONSerialization.data(withJSONObject: object))
    }
    func save(_ session: StoredMemberSession, environment: MemberEnvironment) throws {}
    func remove(environment: MemberEnvironment, household: String) throws {}
}
private actor DigitalFixtureTransport: MemberHTTPTransport {
    var submitted = false
    func send(_ request: URLRequest) async throws -> MemberHTTPReply {
        let path = request.url!.path
        let bytes: Data
        if path == "/auth/session" { bytes = DigitalFixtureData.data("session") }
        else if path.hasSuffix("/submit") { submitted = true; throw URLError(.networkConnectionLost) }
        else if path.hasSuffix("/outcome") && submitted { bytes = DigitalFixtureData.data("committed") }
        else if path.hasSuffix("/cancel") { bytes = Data(#"{"cancelled":true}"#.utf8) }
        else { bytes = DigitalFixtureData.data("prepared") }
        return .init(url: request.url!, status: 200, contentType: "application/json", cacheControl: "no-store", data: bytes)
    }
}
@MainActor private final class DigitalFixturePasskeys: MemberPasskeyAuthorising {
    func authorise(_ ceremony: MemberCeremony, kind: NativePasskeyOptions.Kind) async throws -> MemberPasskeyResponse {
        guard kind == .decision, case .string(let challenge) = ceremony.publicKey["challenge"],
              case .array(let allowed) = ceremony.publicKey["allowCredentials"], case .object(let credential) = allowed[0], case .string(let id) = credential["id"] else { throw NativePasskeyFailure.invalidOptions }
        let data = try JSONSerialization.data(withJSONObject: ["type":"webauthn.get", "origin":"https://unit.example", "challenge":challenge])
        let encoded = data.base64EncodedString().replacingOccurrences(of: "+", with: "-").replacingOccurrences(of: "/", with: "_").replacingOccurrences(of: "=", with: "")
        return .assertion(id: id, clientDataJSON: encoded, authenticatorData: "YQ", signature: "YQ", userHandle: "YQ")
    }
}
@MainActor private final class DigitalFixtureModel: ObservableObject {
    let flow: MemberDigitalFlow
    let client: MemberClient
    let session: MemberSessionInfo
    let detail: MemberOfferDetail
    let draft: MemberDigitalDraft
    @Published var ready = false
    init() {
        session = try! JSONDecoder().decode(MemberSessionInfo.self, from: DigitalFixtureData.data("session"))
        let raw = DigitalFixtureData.value["detail"] as! [String: Any]
        detail = try! MemberOfferDetail.decode(DigitalFixtureData.data("detail"), expectedID: raw["id"] as! String, household: session.household)
        let view = (DigitalFixtureData.value["prepared"] as! [String: Any])["review"] as! [String: Any]
        let approval = try! MemberApproval.decode(JSONSerialization.data(withJSONObject: view["approval"]!), detail: detail)
        var choices = MemberDigitalDraft(approval: approval)
        for candidate in approval.candidates { try! choices.choose(.keep, candidate: candidate.id) }; draft = choices
        let environment = try! MemberEnvironment(name: "test", origin: URL(string: "https://unit.example")!)
        client = MemberClient(environment: environment, transport: DigitalFixtureTransport(), vault: DigitalFixtureVault(info: session), now: { 1_800_000_000_001 })
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent("digital-ui-fixture")
        if ProcessInfo.processInfo.arguments.contains("--fresh") { try? FileManager.default.removeItem(at: directory) }
        flow = MemberDigitalFlow(environment: environment, service: client, passkeys: DigitalFixturePasskeys(), store: try! FileMemberOperationStore(directory: directory), now: { 1_800_000_000_001 })
    }
    func start() async { _ = try? await client.restore(household: session.household); flow.setSession(session); ready = true }
}
struct MemberDigitalFixtureView: View {
    @StateObject private var model = DigitalFixtureModel()
    var body: some View {
        MemberDigitalScreen(flow: model.flow, detail: model.detail, draft: model.draft)
            .disabled(!model.ready)
            .safeAreaInset(edge: .top) { Text("Synthetic digital fixture. No payment or actual passkey.").font(.caption) }
            .task { await model.start() }
    }
}
#endif
